### ISSUE TITLE
Programming

### ISSUE THREAD

**Issue by Jonas-Meyer97** [aspro648/KiCad#2]
Hi,
how did you program the attiny in qnf package?
EDIT: Through the extra ISP connector of course :D

**Comment by aspro648** [comment]
I bought a pretty spendy (~$80USD) QFN20 socket adapter so I could program them before soldering (for the kits).  I also use my Arduino ISP shield (https://www.tindie.com/products/MakersBox/yet-another-programming-shield).  You can, as you figured out, program it through the ISP header after it is soldered.  For that, I use a pogo adapter with the ISP shield: https://www.tindie.com/products/nsayer/avr-isp-pogo-adapter-kit
